# Generated by Django 6.1 on 2026-09-15 14:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfrentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.CharField(choices=[('CUARTOS', 'Cuartos'), ('SEMIFINALES', 'Semifinales'), ('FINAL', 'Final')], default='CUARTOS', max_length=30)),
                ('ganador_enfrentamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_ganados', to='inscripcion.inscripcion')),
                ('participante_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_como_p1', to='inscripcion.inscripcion')),
                ('participante_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_como_p2', to='inscripcion.inscripcion')),
                ('siguiente_enfrentamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torneo.enfrentamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_partidas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('enfrentamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.enfrentamiento')),
                ('ganador_partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscripcion.inscripcion')),
            ],
        ),
    ]
