# Generated by Django 6.1 on 2026-09-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfrentamiento',
            name='victorias_participante_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='victorias_participante_2',
            field=models.IntegerField(default=0),
        ),
    ]
